keys:
  - &gman age1f3axcm808wfxm38lg3qfwllytlgmqcjwn4yenlkyqpg3c3ku532s77e48d
  - &bean age18uzw9yhgjnuy0zg9fajmp75m0r8w93aq0qw453e868mxadflcghqpeqgy4
creation_rules:
  - path_regex: secrets/shared.yaml
    key_groups:
      - age:
          - *gman
  - path_regex: hosts/cypher/secrets.yaml
    key_groups:
      - age:
          - *gman
  - path_regex: hosts/think-one/secrets.yaml
    key_groups:
      - age:
          - *gman
  - path_regex: hosts/somnus/secrets.yaml
    key_groups:
      - age:
          - *bean
  - path_regex: hosts/tater/secrets.yaml
    key_groups:
      - age:
          - *gman
  - path_regex: hosts/gman-theatre/secrets.yaml
    key_groups:
      - age:
          - *gman
