keys:
  - &cypher age1f3axcm808wfxm38lg3qfwllytlgmqcjwn4yenlkyqpg3c3ku532s77e48d
  - &nixos age1rhaqy98rkc67y7da82vgzsturkssekjhv7eawp36qyqx0wjpms9sfl43sj
creation_rules:
  - path_regex: hosts/cypher/secrets.yaml$
    key_groups:
      - age:
        - *cypher
  - path_regex: hosts/nixos/secrets.yaml$
    key_groups:
      - age:
        - *nixos