keys:
  - &cypher age1f3axcm808wfxm38lg3qfwllytlgmqcjwn4yenlkyqpg3c3ku532s77e48d
  - &garth age13mj768x90kcw2m80d0v3px5v2kvhf9dq63a40xxjgyt75kcv0assr0u8eu
  - &somnus age18uzw9yhgjnuy0zg9fajmp75m0r8w93aq0qw453e868mxadflcghqpeqgy4
creation_rules:
  - path_regex: secrets/cypher.yaml$
    key_groups:
      - age:
        - *cypher
  - path_regex: secrets/garth.yaml$
    key_groups:
      - age:
        - *garth
  - path_regex: secrets/somnus.yaml$
    key_groups:
      - age:
        - *somnus