keys:
  - &cypher age1f3axcm808wfxm38lg3qfwllytlgmqcjwn4yenlkyqpg3c3ku532s77e48d
  - &garth age13mj768x90kcw2m80d0v3px5v2kvhf9dq63a40xxjgyt75kcv0assr0u8eu
creation_rules:
  - path_regex: secrets/cypher.yaml$
    key_groups:
      - age:
        - *cypher
  - path_regex: secrets/garth.yaml$
    key_groups:
      - age:
        - *garth