{
  imports = [
    ./audacity.nix
    ./autokey.nix
    ./checkra1n.nix
    ./clipgrab.nix
    ./davinci-resolve.nix
    ./discord
    ./dosbox.nix
    ./filezilla.nix
    ./flips.nix
    ./freeoffice.nix
    ./gcolor.nix
    ./gimp.nix
    ./htop.nix
    ./libreoffice.nix
    ./looking-glass.nix
    ./museeks.nix
    ./musescore.nix
    ./nvtop.nix
    ./obs.nix
    ./obsidian.nix
    ./openshot.nix
    ./pika-backup.nix
    ./powertop.nix
    ./radeontop.nix
    ./remmina.nix
    ./solaar.nix
    ./thunderbird.nix
    ./wireshark.nix
    ./xclicker.nix
  ];
}
